/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appUiRouteRouteImport } from './routes/(app)/ui/route'
import { Route as appDemoRouteRouteImport } from './routes/(app)/demo.route'
import { Route as appUiIndexRouteImport } from './routes/(app)/ui/index'
import { Route as appDemoIndexRouteImport } from './routes/(app)/demo.index'
import { Route as appUiComponentRouteImport } from './routes/(app)/ui/$component'
import { Route as appDemoWebRouteImport } from './routes/(app)/demo.web'
import { Route as appDemoTanstackQueryRouteImport } from './routes/(app)/demo.tanstack-query'
import { Route as appDemoTableRouteImport } from './routes/(app)/demo.table'
import { Route as appDemoKakeiboRouteImport } from './routes/(app)/demo.kakeibo'
import { Route as appDemoFsRouteImport } from './routes/(app)/demo.fs'
import { Route as appDemoChatTRouteImport } from './routes/(app)/demo.chat-t'
import { Route as appDemoChatRouteImport } from './routes/(app)/demo.chat'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appUiRouteRoute = appUiRouteRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => appRouteRoute,
} as any)
const appDemoRouteRoute = appDemoRouteRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => appRouteRoute,
} as any)
const appUiIndexRoute = appUiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appUiRouteRoute,
} as any)
const appDemoIndexRoute = appDemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appDemoRouteRoute,
} as any)
const appUiComponentRoute = appUiComponentRouteImport.update({
  id: '/$component',
  path: '/$component',
  getParentRoute: () => appUiRouteRoute,
} as any)
const appDemoWebRoute = appDemoWebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => appDemoRouteRoute,
} as any)
const appDemoTanstackQueryRoute = appDemoTanstackQueryRouteImport.update({
  id: '/tanstack-query',
  path: '/tanstack-query',
  getParentRoute: () => appDemoRouteRoute,
} as any)
const appDemoTableRoute = appDemoTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => appDemoRouteRoute,
} as any)
const appDemoKakeiboRoute = appDemoKakeiboRouteImport.update({
  id: '/kakeibo',
  path: '/kakeibo',
  getParentRoute: () => appDemoRouteRoute,
} as any)
const appDemoFsRoute = appDemoFsRouteImport.update({
  id: '/fs',
  path: '/fs',
  getParentRoute: () => appDemoRouteRoute,
} as any)
const appDemoChatTRoute = appDemoChatTRouteImport.update({
  id: '/chat-t',
  path: '/chat-t',
  getParentRoute: () => appDemoRouteRoute,
} as any)
const appDemoChatRoute = appDemoChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => appDemoRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/demo': typeof appDemoRouteRouteWithChildren
  '/ui': typeof appUiRouteRouteWithChildren
  '/settings': typeof appSettingsRoute
  '/demo/chat': typeof appDemoChatRoute
  '/demo/chat-t': typeof appDemoChatTRoute
  '/demo/fs': typeof appDemoFsRoute
  '/demo/kakeibo': typeof appDemoKakeiboRoute
  '/demo/table': typeof appDemoTableRoute
  '/demo/tanstack-query': typeof appDemoTanstackQueryRoute
  '/demo/web': typeof appDemoWebRoute
  '/ui/$component': typeof appUiComponentRoute
  '/demo/': typeof appDemoIndexRoute
  '/ui/': typeof appUiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof appSettingsRoute
  '/demo/chat': typeof appDemoChatRoute
  '/demo/chat-t': typeof appDemoChatTRoute
  '/demo/fs': typeof appDemoFsRoute
  '/demo/kakeibo': typeof appDemoKakeiboRoute
  '/demo/table': typeof appDemoTableRoute
  '/demo/tanstack-query': typeof appDemoTanstackQueryRoute
  '/demo/web': typeof appDemoWebRoute
  '/ui/$component': typeof appUiComponentRoute
  '/demo': typeof appDemoIndexRoute
  '/ui': typeof appUiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(app)/demo': typeof appDemoRouteRouteWithChildren
  '/(app)/ui': typeof appUiRouteRouteWithChildren
  '/(app)/settings': typeof appSettingsRoute
  '/(app)/demo/chat': typeof appDemoChatRoute
  '/(app)/demo/chat-t': typeof appDemoChatTRoute
  '/(app)/demo/fs': typeof appDemoFsRoute
  '/(app)/demo/kakeibo': typeof appDemoKakeiboRoute
  '/(app)/demo/table': typeof appDemoTableRoute
  '/(app)/demo/tanstack-query': typeof appDemoTanstackQueryRoute
  '/(app)/demo/web': typeof appDemoWebRoute
  '/(app)/ui/$component': typeof appUiComponentRoute
  '/(app)/demo/': typeof appDemoIndexRoute
  '/(app)/ui/': typeof appUiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/demo'
    | '/ui'
    | '/settings'
    | '/demo/chat'
    | '/demo/chat-t'
    | '/demo/fs'
    | '/demo/kakeibo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/web'
    | '/ui/$component'
    | '/demo/'
    | '/ui/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/demo/chat'
    | '/demo/chat-t'
    | '/demo/fs'
    | '/demo/kakeibo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/web'
    | '/ui/$component'
    | '/demo'
    | '/ui'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/login'
    | '/(app)/demo'
    | '/(app)/ui'
    | '/(app)/settings'
    | '/(app)/demo/chat'
    | '/(app)/demo/chat-t'
    | '/(app)/demo/fs'
    | '/(app)/demo/kakeibo'
    | '/(app)/demo/table'
    | '/(app)/demo/tanstack-query'
    | '/(app)/demo/web'
    | '/(app)/ui/$component'
    | '/(app)/demo/'
    | '/(app)/ui/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/ui': {
      id: '/(app)/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof appUiRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/demo': {
      id: '/(app)/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof appDemoRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/ui/': {
      id: '/(app)/ui/'
      path: '/'
      fullPath: '/ui/'
      preLoaderRoute: typeof appUiIndexRouteImport
      parentRoute: typeof appUiRouteRoute
    }
    '/(app)/demo/': {
      id: '/(app)/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof appDemoIndexRouteImport
      parentRoute: typeof appDemoRouteRoute
    }
    '/(app)/ui/$component': {
      id: '/(app)/ui/$component'
      path: '/$component'
      fullPath: '/ui/$component'
      preLoaderRoute: typeof appUiComponentRouteImport
      parentRoute: typeof appUiRouteRoute
    }
    '/(app)/demo/web': {
      id: '/(app)/demo/web'
      path: '/web'
      fullPath: '/demo/web'
      preLoaderRoute: typeof appDemoWebRouteImport
      parentRoute: typeof appDemoRouteRoute
    }
    '/(app)/demo/tanstack-query': {
      id: '/(app)/demo/tanstack-query'
      path: '/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof appDemoTanstackQueryRouteImport
      parentRoute: typeof appDemoRouteRoute
    }
    '/(app)/demo/table': {
      id: '/(app)/demo/table'
      path: '/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof appDemoTableRouteImport
      parentRoute: typeof appDemoRouteRoute
    }
    '/(app)/demo/kakeibo': {
      id: '/(app)/demo/kakeibo'
      path: '/kakeibo'
      fullPath: '/demo/kakeibo'
      preLoaderRoute: typeof appDemoKakeiboRouteImport
      parentRoute: typeof appDemoRouteRoute
    }
    '/(app)/demo/fs': {
      id: '/(app)/demo/fs'
      path: '/fs'
      fullPath: '/demo/fs'
      preLoaderRoute: typeof appDemoFsRouteImport
      parentRoute: typeof appDemoRouteRoute
    }
    '/(app)/demo/chat-t': {
      id: '/(app)/demo/chat-t'
      path: '/chat-t'
      fullPath: '/demo/chat-t'
      preLoaderRoute: typeof appDemoChatTRouteImport
      parentRoute: typeof appDemoRouteRoute
    }
    '/(app)/demo/chat': {
      id: '/(app)/demo/chat'
      path: '/chat'
      fullPath: '/demo/chat'
      preLoaderRoute: typeof appDemoChatRouteImport
      parentRoute: typeof appDemoRouteRoute
    }
  }
}

interface appDemoRouteRouteChildren {
  appDemoChatRoute: typeof appDemoChatRoute
  appDemoChatTRoute: typeof appDemoChatTRoute
  appDemoFsRoute: typeof appDemoFsRoute
  appDemoKakeiboRoute: typeof appDemoKakeiboRoute
  appDemoTableRoute: typeof appDemoTableRoute
  appDemoTanstackQueryRoute: typeof appDemoTanstackQueryRoute
  appDemoWebRoute: typeof appDemoWebRoute
  appDemoIndexRoute: typeof appDemoIndexRoute
}

const appDemoRouteRouteChildren: appDemoRouteRouteChildren = {
  appDemoChatRoute: appDemoChatRoute,
  appDemoChatTRoute: appDemoChatTRoute,
  appDemoFsRoute: appDemoFsRoute,
  appDemoKakeiboRoute: appDemoKakeiboRoute,
  appDemoTableRoute: appDemoTableRoute,
  appDemoTanstackQueryRoute: appDemoTanstackQueryRoute,
  appDemoWebRoute: appDemoWebRoute,
  appDemoIndexRoute: appDemoIndexRoute,
}

const appDemoRouteRouteWithChildren = appDemoRouteRoute._addFileChildren(
  appDemoRouteRouteChildren,
)

interface appUiRouteRouteChildren {
  appUiComponentRoute: typeof appUiComponentRoute
  appUiIndexRoute: typeof appUiIndexRoute
}

const appUiRouteRouteChildren: appUiRouteRouteChildren = {
  appUiComponentRoute: appUiComponentRoute,
  appUiIndexRoute: appUiIndexRoute,
}

const appUiRouteRouteWithChildren = appUiRouteRoute._addFileChildren(
  appUiRouteRouteChildren,
)

interface appRouteRouteChildren {
  appDemoRouteRoute: typeof appDemoRouteRouteWithChildren
  appUiRouteRoute: typeof appUiRouteRouteWithChildren
  appSettingsRoute: typeof appSettingsRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDemoRouteRoute: appDemoRouteRouteWithChildren,
  appUiRouteRoute: appUiRouteRouteWithChildren,
  appSettingsRoute: appSettingsRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
