/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UiRouteRouteImport } from './routes/ui/route'
import { Route as DemoRouteRouteImport } from './routes/demo.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiIndexRouteImport } from './routes/ui/index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as UiComponentRouteImport } from './routes/ui/$component'
import { Route as DemoWebRouteImport } from './routes/demo.web'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo.table'
import { Route as DemoKakeiboRouteImport } from './routes/demo.kakeibo'
import { Route as DemoFsRouteImport } from './routes/demo.fs'
import { Route as DemoChatTRouteImport } from './routes/demo.chat-t'
import { Route as DemoChatRouteImport } from './routes/demo.chat'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UiRouteRoute = UiRouteRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRouteRoute = DemoRouteRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiIndexRoute = UiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UiRouteRoute,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRouteRoute,
} as any)
const UiComponentRoute = UiComponentRouteImport.update({
  id: '/$component',
  path: '/$component',
  getParentRoute: () => UiRouteRoute,
} as any)
const DemoWebRoute = DemoWebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/tanstack-query',
  path: '/tanstack-query',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoKakeiboRoute = DemoKakeiboRouteImport.update({
  id: '/kakeibo',
  path: '/kakeibo',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoFsRoute = DemoFsRouteImport.update({
  id: '/fs',
  path: '/fs',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoChatTRoute = DemoChatTRouteImport.update({
  id: '/chat-t',
  path: '/chat-t',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoChatRoute = DemoChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DemoRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteRouteWithChildren
  '/ui': typeof UiRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/demo/chat': typeof DemoChatRoute
  '/demo/chat-t': typeof DemoChatTRoute
  '/demo/fs': typeof DemoFsRoute
  '/demo/kakeibo': typeof DemoKakeiboRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/web': typeof DemoWebRoute
  '/ui/$component': typeof UiComponentRoute
  '/demo/': typeof DemoIndexRoute
  '/ui/': typeof UiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/demo/chat': typeof DemoChatRoute
  '/demo/chat-t': typeof DemoChatTRoute
  '/demo/fs': typeof DemoFsRoute
  '/demo/kakeibo': typeof DemoKakeiboRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/web': typeof DemoWebRoute
  '/ui/$component': typeof UiComponentRoute
  '/demo': typeof DemoIndexRoute
  '/ui': typeof UiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteRouteWithChildren
  '/ui': typeof UiRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/demo/chat': typeof DemoChatRoute
  '/demo/chat-t': typeof DemoChatTRoute
  '/demo/fs': typeof DemoFsRoute
  '/demo/kakeibo': typeof DemoKakeiboRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/web': typeof DemoWebRoute
  '/ui/$component': typeof UiComponentRoute
  '/demo/': typeof DemoIndexRoute
  '/ui/': typeof UiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/ui'
    | '/login'
    | '/settings'
    | '/demo/chat'
    | '/demo/chat-t'
    | '/demo/fs'
    | '/demo/kakeibo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/web'
    | '/ui/$component'
    | '/demo/'
    | '/ui/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/demo/chat'
    | '/demo/chat-t'
    | '/demo/fs'
    | '/demo/kakeibo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/web'
    | '/ui/$component'
    | '/demo'
    | '/ui'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/ui'
    | '/login'
    | '/settings'
    | '/demo/chat'
    | '/demo/chat-t'
    | '/demo/fs'
    | '/demo/kakeibo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/web'
    | '/ui/$component'
    | '/demo/'
    | '/ui/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRouteRoute: typeof DemoRouteRouteWithChildren
  UiRouteRoute: typeof UiRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/': {
      id: '/ui/'
      path: '/'
      fullPath: '/ui/'
      preLoaderRoute: typeof UiIndexRouteImport
      parentRoute: typeof UiRouteRoute
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/ui/$component': {
      id: '/ui/$component'
      path: '/$component'
      fullPath: '/ui/$component'
      preLoaderRoute: typeof UiComponentRouteImport
      parentRoute: typeof UiRouteRoute
    }
    '/demo/web': {
      id: '/demo/web'
      path: '/web'
      fullPath: '/demo/web'
      preLoaderRoute: typeof DemoWebRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/kakeibo': {
      id: '/demo/kakeibo'
      path: '/kakeibo'
      fullPath: '/demo/kakeibo'
      preLoaderRoute: typeof DemoKakeiboRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/fs': {
      id: '/demo/fs'
      path: '/fs'
      fullPath: '/demo/fs'
      preLoaderRoute: typeof DemoFsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/chat-t': {
      id: '/demo/chat-t'
      path: '/chat-t'
      fullPath: '/demo/chat-t'
      preLoaderRoute: typeof DemoChatTRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/chat': {
      id: '/demo/chat'
      path: '/chat'
      fullPath: '/demo/chat'
      preLoaderRoute: typeof DemoChatRouteImport
      parentRoute: typeof DemoRouteRoute
    }
  }
}

interface DemoRouteRouteChildren {
  DemoChatRoute: typeof DemoChatRoute
  DemoChatTRoute: typeof DemoChatTRoute
  DemoFsRoute: typeof DemoFsRoute
  DemoKakeiboRoute: typeof DemoKakeiboRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoWebRoute: typeof DemoWebRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteRouteChildren: DemoRouteRouteChildren = {
  DemoChatRoute: DemoChatRoute,
  DemoChatTRoute: DemoChatTRoute,
  DemoFsRoute: DemoFsRoute,
  DemoKakeiboRoute: DemoKakeiboRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoWebRoute: DemoWebRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteRouteWithChildren = DemoRouteRoute._addFileChildren(
  DemoRouteRouteChildren,
)

interface UiRouteRouteChildren {
  UiComponentRoute: typeof UiComponentRoute
  UiIndexRoute: typeof UiIndexRoute
}

const UiRouteRouteChildren: UiRouteRouteChildren = {
  UiComponentRoute: UiComponentRoute,
  UiIndexRoute: UiIndexRoute,
}

const UiRouteRouteWithChildren =
  UiRouteRoute._addFileChildren(UiRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRouteRoute: DemoRouteRouteWithChildren,
  UiRouteRoute: UiRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
