/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteRouteImport } from './routes/demo.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoWebRouteImport } from './routes/demo.web'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo.table'
import { Route as DemoKakeiboRouteImport } from './routes/demo.kakeibo'
import { Route as DemoFsRouteImport } from './routes/demo.fs'
import { Route as DemoChatTRouteImport } from './routes/demo.chat-t'
import { Route as DemoChatRouteImport } from './routes/demo.chat'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRouteRoute = DemoRouteRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoWebRoute = DemoWebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/tanstack-query',
  path: '/tanstack-query',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoKakeiboRoute = DemoKakeiboRouteImport.update({
  id: '/kakeibo',
  path: '/kakeibo',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoFsRoute = DemoFsRouteImport.update({
  id: '/fs',
  path: '/fs',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoChatTRoute = DemoChatTRouteImport.update({
  id: '/chat-t',
  path: '/chat-t',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoChatRoute = DemoChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DemoRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/demo/chat': typeof DemoChatRoute
  '/demo/chat-t': typeof DemoChatTRoute
  '/demo/fs': typeof DemoFsRoute
  '/demo/kakeibo': typeof DemoKakeiboRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/web': typeof DemoWebRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/demo/chat': typeof DemoChatRoute
  '/demo/chat-t': typeof DemoChatTRoute
  '/demo/fs': typeof DemoFsRoute
  '/demo/kakeibo': typeof DemoKakeiboRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/web': typeof DemoWebRoute
  '/demo': typeof DemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/demo/chat': typeof DemoChatRoute
  '/demo/chat-t': typeof DemoChatTRoute
  '/demo/fs': typeof DemoFsRoute
  '/demo/kakeibo': typeof DemoKakeiboRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/web': typeof DemoWebRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/demo/chat'
    | '/demo/chat-t'
    | '/demo/fs'
    | '/demo/kakeibo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/web'
    | '/demo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/demo/chat'
    | '/demo/chat-t'
    | '/demo/fs'
    | '/demo/kakeibo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/web'
    | '/demo'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/login'
    | '/demo/chat'
    | '/demo/chat-t'
    | '/demo/fs'
    | '/demo/kakeibo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/web'
    | '/demo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRouteRoute: typeof DemoRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/web': {
      id: '/demo/web'
      path: '/web'
      fullPath: '/demo/web'
      preLoaderRoute: typeof DemoWebRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/kakeibo': {
      id: '/demo/kakeibo'
      path: '/kakeibo'
      fullPath: '/demo/kakeibo'
      preLoaderRoute: typeof DemoKakeiboRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/fs': {
      id: '/demo/fs'
      path: '/fs'
      fullPath: '/demo/fs'
      preLoaderRoute: typeof DemoFsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/chat-t': {
      id: '/demo/chat-t'
      path: '/chat-t'
      fullPath: '/demo/chat-t'
      preLoaderRoute: typeof DemoChatTRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/chat': {
      id: '/demo/chat'
      path: '/chat'
      fullPath: '/demo/chat'
      preLoaderRoute: typeof DemoChatRouteImport
      parentRoute: typeof DemoRouteRoute
    }
  }
}

interface DemoRouteRouteChildren {
  DemoChatRoute: typeof DemoChatRoute
  DemoChatTRoute: typeof DemoChatTRoute
  DemoFsRoute: typeof DemoFsRoute
  DemoKakeiboRoute: typeof DemoKakeiboRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoWebRoute: typeof DemoWebRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteRouteChildren: DemoRouteRouteChildren = {
  DemoChatRoute: DemoChatRoute,
  DemoChatTRoute: DemoChatTRoute,
  DemoFsRoute: DemoFsRoute,
  DemoKakeiboRoute: DemoKakeiboRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoWebRoute: DemoWebRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteRouteWithChildren = DemoRouteRoute._addFileChildren(
  DemoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRouteRoute: DemoRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
